### ISSUE TITLE
cannot import name 'create_model' from 'models' (unknown location)

### ISSUE THREAD

**Issue by tprdk** [seungho-snu/FxSR#2]
Thanks for your great work. 
I just run the test.py file as mentioned in quick_test_guide.txt. But it gives me "cannot import name 'create_model' from 'models' (unknown location)" error . How can i load pretrained model and test with my custom dataset?

**Comment by seogihyun** [comment]
> Thanks for your great work. I just run the test.py file as mentioned in quick_test_guide.txt. But it gives me "cannot import name 'create_model' from 'models' (unknown location)" error . How can i load pretrained model and test with my custom dataset?

I think the reason is that they didn't upload relative other codes.

**Comment by seungho-snu** [comment]
Thanks for your comments. I fixed the problems you mentioned and updated modified codes.
Please let me know If you have any other problem.
 
 
-----Original Message-----

**Comment by tprdk** [comment]
Thanks for your reply. I will try it asap.

**Comment by seungho-snu** [comment]
Please let me know If you have any other problem.
