### ISSUE TITLE
how to test General100 datasets?using bicubic downsampling?

### ISSUE THREAD

**Issue by Lisbegin** [seungho-snu/FxSR#3]
First of all, I think it is very interesting for your research, but I want to know how your General100 data set is tested. This data set only has GT. Did you directly use bicubic downsampling to obtain low-quality pictures? I directly use the test pair obtained by bicubic downsampling, and the effect of the model test is not very satisfactory

**Comment by seungho-snu** [comment]
Thank you for your interest. Yes, I used bicubic downsampling.
